import {createTheme} from '@shopify/restyle';
const palette = {
  green: '#0E6B6E',
  greenLight: '#EAF6F6',
  carrot: '#F86F2D',
  carrotLight: '#FAE6DD',
  greenSuccess: '#4ABC86',
  greenSuccessLight: '#D8FFEC',
  redError: '#EA3838',
  redErrorLight: '#FBECEC',
  grayBlack: '#000000',
  gray1: '#636363',
  gray2: '#8E8E8E',
  gray3: '#B3B3B3',
  gray4: '#E1E1E1',
  gray5: '#F5F5F5',
  grayWhite: '#FFFFFF',
  yellow: '#FFD700',
  yellowLight: '#FFF8DC',
  blueDark: '#4B5563',
  blueDarkLight: '#E5EAF2',
};
export const theme = createTheme({
  colors: {
    ...palette,
    primary: palette.green,
    primaryContrast: palette.grayWhite,
    buttonPrimary: palette.green,
    background: palette.grayWhite,
    backgroundContrast: palette.grayBlack,
    error: palette.redError,
    errorLight: palette.redErrorLight,
    success: palette.greenSuccess,
    successLight: palette.greenSuccessLight,
  },
  spacing: {
    s0: 0,
    s4: 4,
    s6: 6,
    s8: 8,
    s10: 10,
    s12: 12,
    s14: 14,
    s16: 16,
    s20: 20,
    s24: 24,
    s32: 32,
    s40: 40,
    s48: 48,
    s56: 56,
  },
  borderRadii: {
    s8: 8,
    s12: 12,
    s16: 16,
  },
  textVariants: {
    defaults: {},
  },
});
export type Theme = typeof theme;
export type ThemeColors = keyof Theme['colors'];
